import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./components//layout/navbar/Navbar";
import { Footer } from "@/app/components/layout/footer/Footer";
import { companies, getCompanyBySlug } from "@/data/companies";

import "./globals.css";

const FALLBACK_SLUG = "tso-texas";

async function getCompany() {
  const headersList = await headers();
  const slug = headersList.get("x-company-slug") ?? FALLBACK_SLUG;
  return getCompanyBySlug(slug) || getCompanyBySlug(FALLBACK_SLUG)!;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const company = await getCompany();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar company={company} />
        {children}
        <Footer company={company} />
      </body>
    </html>
  );
}
